spring.application.name=bigProject
management.endpoints.web.exposure.include=*
management.info.env.enabled=true

management.endpoints.web.exposure.exclude=health,info
info.app.name= srinivas app
info.app.description=this app tells the basics of spring boot
info.app.version=1.0.0


coach.name=sam sigh
team.name= ratan
